require("lodash");
require("react");
require("react-dom");
require("react-redux");
require("redux");
require("redux-logger");
require("leaflet");
require("babel-cli");
// require("babel-core");
// require("babel-loader");
require("babel-plugin-add-module-exports");
require("babel-polyfill");
// require("babel-preset-es2015");
require("babel-preset-react");
// require("css-loader");
// require("install");
// require("node-sass");
require("react-hot-loader");
require("redux-devtools");
// require("sass-loader");
// require("style-loader");