# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 18:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_polygon_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='line',
            name='file',
            field=models.FileField(upload_to='lines/'),
        ),
        migrations.AlterField(
            model_name='line',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='point',
            name='file',
            field=models.FileField(upload_to='points/'),
        ),
        migrations.AlterField(
            model_name='point',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='file',
            field=models.FileField(upload_to='polygons/'),
        ),
    ]
