# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 10:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161127_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.RenameModel(
            old_name='Line',
            new_name='LineModel',
        ),
        migrations.RenameModel(
            old_name='Point',
            new_name='PointModel',
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
    ]
