# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_geometrymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrymodel',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
