# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 21:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_geometrymodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarshbjGeoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('geom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GeometryModel',
        ),
        migrations.DeleteModel(
            name='LineModel',
        ),
        migrations.DeleteModel(
            name='PointModel',
        ),
        migrations.DeleteModel(
            name='PolygonModel',
        ),
    ]
